-- stoic_prompts.lua
-- 365 Daily Stoic Journal Prompts
-- Inspired by "The Daily Stoic" by Ryan Holiday

local M = {}

-- Prompts indexed by month (1-12) and day (1-31)
M.prompts = {
  -- JANUARY: Clarity
  [1] = {
    [1] = "What things are truly in my control?",
    [2] = "What am I learning and studying for?",
    [3] = "What can I say no to so I can say yes to what matters?",
    [4] = "Am I seeing clearly? Acting generously? Accepting what I can't change?",
    [5] = "What is my purpose in life?",
    [6] = "Who am I and what do I stand for?",
    [7] = "How can I keep my mind clear from pollution?",
    [8] = "What am I addicted to?",
    [9] = "If I don't control what happens to me, what is left?",
    [10] = "Where can I find steadiness?",
    [11] = "What are sources of unsteadiness in my life?",
    [12] = "Where is the path to serenity?",
    [13] = "What can I put outside my circle of control?",
    [14] = "What jerks me around?",
    [15] = "Am I staying the course or being steered away?",
    [16] = "What assumptions have I left unquestioned?",
    [17] = "Am I doing work that matters?",
    [18] = "Can I find grace and harmony in places others overlook?",
    [19] = "Good or bad, high or low, do I still have choices?",
    [20] = "How can I rekindle my principles and start living today?",
    [21] = "What am I getting out of my journaling ritual?",
    [22] = "What bad habit did I curb today?",
    [23] = "Which of my possessions own me?",
    [24] = "Am I doing deep work?",
    [25] = "What do I truly prize?",
    [26] = "What is my mantra today?",
    [27] = "What am I studying, practicing, and training?",
    [28] = "What ruler do I measure myself against?",
    [29] = "Am I keeping a sturdy mind on the task at hand?",
    [30] = "Am I content to be clueless about things that don't matter?",
    [31] = "What healing can philosophy help me find today?",
  },

  -- FEBRUARY: Passions and Emotions
  [2] = {
    [1] = "How can I conquer my temper?",
    [2] = "What impulses rob me of self-control?",
    [3] = "Am I in control or is my anxiety?",
    [4] = "Am I cultivating the invincibility of my power to choose?",
    [5] = "Am I thinking before I act?",
    [6] = "What needless conflict can I avoid?",
    [7] = "How can I conquer fear and worry—before they conquer me?",
    [8] = "Do my outbursts ever make things better?",
    [9] = "What if I didn't have an opinion about this?",
    [10] = "What parts of my life are driven by anger?",
    [11] = "Is my soul a good ruler or a tyrant?",
    [12] = "For what have I sold my peace of mind?",
    [13] = "Which of my pleasures are really punishments?",
    [14] = "How can I do a better job listening to the little voice inside me?",
    [15] = "Do these strong emotions even make sense?",
    [16] = "What am I making harder than it needs to be?",
    [17] = "What happiness am I putting off that I could have right now?",
    [18] = "Am I in rigorous training against false impressions?",
    [19] = "Am I happy with my portion at the banquet of life?",
    [20] = "Are the pleasures I'm chasing actually worth it?",
    [21] = "What can I stop yearning for?",
    [22] = "Am I certain what I want to say isn't better left unsaid?",
    [23] = "Why get angry at things, if anger doesn't change it?",
    [24] = "Why am I telling myself that I've been harmed?",
    [25] = "Will I even remember this fight in a few months?",
    [26] = "Why do I need to care that someone else screwed up?",
    [27] = "How can I cultivate indifference to unimportant things?",
    [28] = "What would happen if I took a second to cool down?",
    [29] = "You can't always be getting what you want—can I accept that today?",
  },

  -- MARCH: Awareness
  [3] = {
    [1] = "How often do I question the things others take for granted?",
    [2] = "Do I see and assess myself accurately?",
    [3] = "Am I standing with the philosopher or the mob?",
    [4] = "How many of my limitations are really self-imposed?",
    [5] = "Do I really need these things I work so hard for?",
    [6] = "Where am I a loudmouth?",
    [7] = "Can I test my own opinion before trusting it?",
    [8] = "Am I protecting my time and attention?",
    [9] = "Does my social circle make me better or worse?",
    [10] = "Who is my role model? Why?",
    [11] = "Where have I traded away freedom? How can I get it back?",
    [12] = "What would change if I looked for other people's good intentions?",
    [13] = "Instead of calling it bad luck, can I come to see it as inevitable?",
    [14] = "How is my arrogance preventing me from learning?",
    [15] = "What would it be like if I focused entirely on the present moment?",
    [16] = "Do I appreciate this mind I have been given?",
    [17] = "Are my choices beautiful?",
    [18] = "What bad assumptions can I cast out?",
    [19] = "What is the real cause of my irritations—external things or my opinions?",
    [20] = "Am I cultivating the virtue that makes adversity bearable?",
    [21] = "What if I sought peace where I am right now instead of in distant lands?",
    [22] = "Have I confused schooling and education?",
    [23] = "How can I treat my greedy vices? How can I heal my sickness?",
    [24] = "What philosophical lessons can I find in ordinary things?",
    [25] = "Would I feel wealthier if I decreased my wants?",
    [26] = "Am I keeping watch?",
    [27] = "What valuable things do I sell too cheaply?",
    [28] = "Is my training designed to help me rise to the occasion?",
    [29] = "Why do I care so much about impressing people?",
    [30] = "If I'm not ruled by reason, what am I ruled by?",
    [31] = "Can I stop chasing the impossible today?",
  },

  -- APRIL: Unbiased Thought
  [4] = {
    [1] = "What thoughts are coloring my world?",
    [2] = "What can I do today to keep drama away?",
    [3] = "Are my plans at war with my other plans?",
    [4] = "Can I fight to be the person philosophy wants me to be today?",
    [5] = "What would happen if I stopped to verify my opinions and initial reactions?",
    [6] = "Despite the worst things people do, can I love them anyway?",
    [7] = "Where are my opinions part of the problem?",
    [8] = "What bad assumptions, habits, or advice have I accepted?",
    [9] = "Can I step back and test my impressions? What would I find if I did?",
    [10] = "How do my judgments cause me anguish?",
    [11] = "Can I stop thinking I already know and learn something here?",
    [12] = "What's the truth about so-called 'honors' and 'riches'?",
    [13] = "What would less look like?",
    [14] = "Do I balance my life better than the balance sheet of my business?",
    [15] = "Life is full of taxes—am I prepared to pay them?",
    [16] = "What can I pay closer attention to today?",
    [17] = "Can I stop feeling hurt by every little thing?",
    [18] = "Do I need to have an opinion about this?",
    [19] = "Am I leaving room for what might happen?",
    [20] = "How long can I go without letting my attention slide?",
    [21] = "How long can I maintain focus on what truly matters?",
    [22] = "Am I self-aware, self-critical, and self-determining?",
    [23] = "How am I caring for my mind?",
    [24] = "Nice cars, jewels, fine wine—what are these things really?",
    [25] = "Am I willing to admit when I'm wrong?",
    [26] = "How can I learn from my sparring partners?",
    [27] = "How long does praise really last anyway?",
    [28] = "What power does all my wanting take from me?",
    [29] = "What do I feel when I look up at the sky?",
    [30] = "Do my actions match my character?",
  },

  -- MAY: Right Action
  [5] = {
    [1] = "Do my actions—and my mind—match my philosophy?",
    [2] = "What kind of person do I want to be?",
    [3] = "Am I showing or telling?",
    [4] = "Where can I spend money to help others?",
    [5] = "Have I made myself a lifelong project?",
    [6] = "Am I seeking the beauty of human excellence?",
    [7] = "What is some good I can get from myself today?",
    [8] = "What evil comes from my own choices?",
    [9] = "Will I seize this day?",
    [10] = "What bold thing can I do today?",
    [11] = "Where does my lack of self-control create problems?",
    [12] = "What would happen if I responded with kindness, no matter what?",
    [13] = "Which bad habits am I fueling?",
    [14] = "Are my actions contributing to my well-being?",
    [15] = "What blessings can I count right now?",
    [16] = "How am I creating momentum for my good habits?",
    [17] = "Am I on the path to progress?",
    [18] = "Is my attention actually on the things at hand?",
    [19] = "Where am I doing the opposite of what I should?",
    [20] = "What are the seeds I'm planting and what will they grow?",
    [21] = "Can I take a blow and stay in the ring?",
    [22] = "Can I be a good person right here, right now?",
    [23] = "Can I start living right here, right now?",
    [24] = "How can I make my own good fortune?",
    [25] = "What kind of selfless things will bring me joy?",
    [26] = "What if I stopped caring what others thought?",
    [27] = "What small stuff should I sweat?",
    [28] = "What should I think about before I take action?",
    [29] = "What work nourishes my mind?",
    [30] = "Is my hard work for the right end?",
    [31] = "If my vocation is to be a good person, am I doing a good job?",
  },

  -- JUNE: Problem Solving
  [6] = {
    [1] = "Do I have a backup option in mind for all things?",
    [2] = "Where have I lost the forest for the trees?",
    [3] = "Do I have a backup plan for my backup plan?",
    [4] = "Do I realize how tough and strong I am capable of being?",
    [5] = "Can I blow my own nose—instead of asking someone to do it for me?",
    [6] = "Is this a time to stick or to quit?",
    [7] = "What mentors do I follow—alive or dead?",
    [8] = "If I took things patiently, step by step, what could I conquer?",
    [9] = "What do I need to nip in the bud right now?",
    [10] = "If someone else was strong enough to do it, why can't I?",
    [11] = "How often is anger more destructive than what caused it?",
    [12] = "Am I learning to be adaptable?",
    [13] = "Am I fulfilling my post in this campaign of life, or sleeping on duty?",
    [14] = "Do I have a hold on the right handle of this situation?",
    [15] = "Can I listen more and talk less today?",
    [16] = "Where do I need help? Who can I ask for it?",
    [17] = "What am I blaming on chance or luck that's really on me?",
    [18] = "Am I ready and able?",
    [19] = "How can I better keep myself in the present moment?",
    [20] = "Am I the calm one in the room or the one who needs to be calmed?",
    [21] = "How can I refresh my mind today?",
    [22] = "Am I actually learning from my failures?",
    [23] = "Where am I standing in my own way?",
    [24] = "Do I really need to argue and quarrel so much?",
    [25] = "Am I expecting the possible, and not just what I want?",
    [26] = "What thing do I always do that fails and what if I tried the opposite?",
    [27] = "What can this adversity show me?",
    [28] = "What can I stop beating myself up over?",
    [29] = "How can I anticipate and adapt to what's coming?",
    [30] = "How can I use this obstacle as an opportunity?",
  },

  -- JULY: Duty
  [7] = {
    [1] = "As a Stoic, what is my job?",
    [2] = "What is the harder choice I'm avoiding?",
    [3] = "What if I saw opportunities instead of obligation?",
    [4] = "Am I keeping the flame of virtue burning?",
    [5] = "Am I doing the honorable thing?",
    [6] = "Am I dragging my feet or am I doing my job as a human being?",
    [7] = "Can I show Odysseus-like determination and perseverance?",
    [8] = "What painful things can I take responsibility for?",
    [9] = "Am I on the philosopher's path or winging it?",
    [10] = "Am I dedicated to my craft?",
    [11] = "How will I improve myself today?",
    [12] = "What principles govern my behavior?",
    [13] = "Am I ready to be a leader? Ready to do my job?",
    [14] = "What duties am I neglecting that deserve my attention?",
    [15] = "Can I do the right thing—even without the promise of rewards?",
    [16] = "To what service am I committed?",
    [17] = "Where have I abandoned others?",
    [18] = "Can I mind my own business and not be distracted by others?",
    [19] = "What would forgiveness feel like?",
    [20] = "Am I living a just life?",
    [21] = "How can I work better with others?",
    [22] = "Am I acting nobly or grudgingly?",
    [23] = "How can I make sure none of it goes to my head—good or bad?",
    [24] = "Can I keep my cool when receiving disturbing news?",
    [25] = "Where do I let work diminish my quality of life?",
    [26] = "Where can I pitch in? How can I help?",
    [27] = "What is better than virtue?",
    [28] = "Where have I been privileged—and what am I doing with it?",
    [29] = "Where can I find confidence?",
    [30] = "Can I seek joy today in purpose, excellence, and duty?",
    [31] = "Am I neglecting the personal for the professional?",
  },

  -- AUGUST: Pragmatism
  [8] = {
    [1] = "Where does my idealism hold me back?",
    [2] = "How can I make do with the tough situations I face?",
    [3] = "Can I get the most out of where I am right here, right now?",
    [4] = "How can I avoid fruitless emotions today?",
    [5] = "Can I hold my tongue today?",
    [6] = "What small progress can I make today?",
    [7] = "Can I live well no matter how trying the environment?",
    [8] = "What's the smallest step I can take toward a big thing today?",
    [9] = "Can I keep things simple today? Straightforward?",
    [10] = "Where is perfectionism holding me back?",
    [11] = "Are my habits getting better?",
    [12] = "Am I making this philosophy my own by putting it into practice?",
    [13] = "What troubles can I solve in advance?",
    [14] = "How will philosophy help steer my course today?",
    [15] = "Will decisions I make today be based on true judgments?",
    [16] = "How will I turn today's adversities into advantages?",
    [17] = "Can I go a whole day without blaming others?",
    [18] = "What practical wisdom can I apply to today's challenges?",
    [19] = "What inessential things can I eliminate from my life?",
    [20] = "How well is my soul dressed?",
    [21] = "What if I stopped worrying about the future and enjoyed the present?",
    [22] = "What small stuff can I stop sweating?",
    [23] = "Where do I have too much of a good thing?",
    [24] = "What can I learn from others—even the people I don't like?",
    [25] = "What new path can I blaze today?",
    [26] = "What potential losses can I anticipate in advance?",
    [27] = "Where can I learn to laugh rather than cry?",
    [28] = "What luxuries can I practice not needing?",
    [29] = "What wants can I eliminate today?",
    [30] = "Can I do today's duties with both courage and confidence?",
    [31] = "Where have I done others wrong?",
  },

  -- SEPTEMBER: Fortitude and Resilience
  [9] = {
    [1] = "Am I working to make my soul stronger than any Fortune?",
    [2] = "What's the most painful part of Stoicism for me?",
    [3] = "How am I preparing in the off-season for what is to come?",
    [4] = "How can I see these difficulties as a lesson and a test?",
    [5] = "What inner strength am I building through today's challenges?",
    [6] = "If I lost my freedom, would it break me?",
    [7] = "How will I use the power of choice today?",
    [8] = "Am I prepared for my bubble to be burst?",
    [9] = "Do I rule my fears, or do they rule me?",
    [10] = "How can I prepare for the losses I fear?",
    [11] = "Where can I do with less today?",
    [12] = "Where am I putting our affairs?",
    [13] = "How strong is my Inner Citadel?",
    [14] = "Am I praying—or demanding?",
    [15] = "Am I sizzle or steak?",
    [16] = "Will I triumph over the disasters and panics of the day?",
    [17] = "Can I resist giving in to haters—and hating them in return?",
    [18] = "Can I let the pains of life pass without adding to them?",
    [19] = "Am I flexible enough to change my mind and accept feedback?",
    [20] = "How ready am I for unexpected attacks?",
    [21] = "Can I keep life's rhythm no matter the interruption?",
    [22] = "How will today's difficulties show my character?",
    [23] = "How is my training coming?",
    [24] = "Have I thought about all that might happen?",
    [25] = "What am I a slave to?",
    [26] = "What idle leisure can I replace with something more fulfilling?",
    [27] = "What do prosperity and difficulty each reveal about me?",
    [28] = "How will I respond to the things that happen today?",
    [29] = "Where are my eyes bigger than my stomach?",
    [30] = "How can I strengthen my Inner Citadel?",
  },

  -- OCTOBER: Virtue and Kindness
  [10] = {
    [1] = "How will I let my virtues shine today?",
    [2] = "If wisdom is the most valuable asset, how have I invested in it?",
    [3] = "Do I live as if we are all one—all part of the same whole?",
    [4] = "Will my actions today be good for all concerned?",
    [5] = "What do I say that's better left unsaid?",
    [6] = "Who else can I root for—other than myself?",
    [7] = "Why does my wrongdoing hurt me most of all?",
    [8] = "What is more pleasing than wisdom?",
    [9] = "Have I set my standards and am I using them?",
    [10] = "What do my principles tell me about persisting and resisting?",
    [11] = "Is honesty my default setting?",
    [12] = "Instead of seeking love can I give it first?",
    [13] = "Has revenge ever made anything better?",
    [14] = "Instead of getting mad, how can I help?",
    [15] = "Will I give people the benefit of the doubt?",
    [16] = "How can I share this philosophy that has helped me so much?",
    [17] = "Where can I show other people kindness?",
    [18] = "Am I avoiding false friendships and bad influences?",
    [19] = "Which good habit can I use today to drive out a bad one?",
    [20] = "Do my principles show themselves in my life?",
    [21] = "Can I do the right thing and not care about credit?",
    [22] = "Am I actually improving—or am I just chasing vanity?",
    [23] = "Am I displaying my best qualities?",
    [24] = "What goodness can I find inside myself? Can I bring it to the surface?",
    [25] = "What are my tasks in this life?",
    [26] = "Are my goals natural, moral, and rational?",
    [27] = "What bad behaviors or choices have come back to haunt me?",
    [28] = "What can I do to be part of something bigger than myself?",
    [29] = "How can I improve my character?",
    [30] = "What time can I claw back for myself—and how will I use it?",
    [31] = "What good turns can be done today?",
  },

  -- NOVEMBER: Acceptance
  [11] = {
    [1] = "Can I love everything that happens today?",
    [2] = "Can I make my choices and accept whatever will be?",
    [3] = "How can this be exactly what I needed?",
    [4] = "Is change really so bad? Is the status quo really so good?",
    [5] = "Is my character producing a well-flowing life?",
    [6] = "Am I prepared for the randomness of fate and luck?",
    [7] = "Am I trying to master myself—or other people?",
    [8] = "What's my role in the play of life?",
    [9] = "What principles will steer me through the flow of change?",
    [10] = "What will remain when all else passes away?",
    [11] = "What false judgment can I wipe away today?",
    [12] = "Can the buck stop with me today?",
    [13] = "Does complaining accomplish anything?",
    [14] = "Will I add negative thoughts on top of my troubles?",
    [15] = "Will I embrace the flow of change today?",
    [16] = "Can I cease both hoping for and fearing certain outcomes?",
    [17] = "Is it really my place to judge other people?",
    [18] = "Am I practicing good Stoic thoughts?",
    [19] = "Will I accept the situation and still fight to do and be good?",
    [20] = "Where can I find timelessness in every moment?",
    [21] = "How can I make this minute—right now—be enough?",
    [22] = "What am I irrationally afraid of losing?",
    [23] = "Why is my power to choose so resilient and adaptable?",
    [24] = "How can I see my loved ones as gifts not possessions?",
    [25] = "Is more money really going to make things better?",
    [26] = "What petty comparisons am I bothering myself with?",
    [27] = "What sources of unrest can I tune out?",
    [28] = "What's bothering me that I haven't spoken up about?",
    [29] = "How can I be less agitated—and complain about it less, too?",
    [30] = "Am I ready to accept the pull of the universe?",
  },

  -- DECEMBER: Meditation on Mortality
  [12] = {
    [1] = "If I lived today as if it were my last, what would I do?",
    [2] = "How can I make my actions count?",
    [3] = "What practical problems am I solving with this philosophy?",
    [4] = "What do I truly own?",
    [5] = "What unpleasant thoughts can I face and use to my advantage?",
    [6] = "What can I do to live now, while I still can?",
    [7] = "Can I love the hand Fate deals me?",
    [8] = "Are there any feelings I need to face?",
    [9] = "Am I saying no enough?",
    [10] = "What am I getting in return for the time I spend so freely?",
    [11] = "Am I living with dignity and courage?",
    [12] = "Will I keep the rhythm of life, no matter the interruptions?",
    [13] = "Can I be grateful for the time I've been given?",
    [14] = "What will my life be a testament to?",
    [15] = "Am I going to get a little bit better today?",
    [16] = "What am I doing to build my self-confidence?",
    [17] = "How well do I really know myself?",
    [18] = "The end for us all is clear, but is my purpose?",
    [19] = "What can I focus on that is much, much bigger than me?",
    [20] = "What am I really so afraid of?",
    [21] = "How can I make the most of today—and in doing so, my life?",
    [22] = "What wisdom will I create today?",
    [23] = "If I relaxed my tight grip on life, what would happen?",
    [24] = "Can I consume less to make more room for virtue?",
    [25] = "Where can I find reinvigoration and balance?",
    [26] = "Where am I wasting life?",
    [27] = "Is my soul stronger than my body?",
    [28] = "In a hundred years, who will remember or be remembered?",
    [29] = "What am I grateful for?",
    [30] = "How can I bring a calm mind to tough situations?",
    [31] = "How will I turn these words into works?",
  },
}

-- Monthly themes for context
M.themes = {
  [1] = "Clarity",
  [2] = "Passions and Emotions",
  [3] = "Awareness",
  [4] = "Unbiased Thought",
  [5] = "Right Action",
  [6] = "Problem Solving",
  [7] = "Duty",
  [8] = "Pragmatism",
  [9] = "Fortitude and Resilience",
  [10] = "Virtue and Kindness",
  [11] = "Acceptance",
  [12] = "Meditation on Mortality",
}

-- Get prompt for a specific date
function M.get_prompt(month, day)
  if M.prompts[month] and M.prompts[month][day] then
    return M.prompts[month][day]
  end
  return "What wisdom will guide me today?"
end

-- Get theme for a month
function M.get_theme(month)
  return M.themes[month] or "Stoic Reflection"
end

-- Get formatted prompt with theme
function M.get_formatted(month, day)
  local prompt = M.get_prompt(month, day)
  local theme = M.get_theme(month)
  return string.format("**%s:** %s", theme, prompt)
end

return M
